### ISSUE TITLE
Add support for multiple collections in `json` mode

### ISSUE THREAD

**Issue by feliixx** [feliixx/mongoplayground#1]
**TODO**: 

  - [x] define the new syntax. It has to be backward compatible 
  - [x] update javascript BSON parser
  - [x] add a combobox with templates ( `single collection`,`multiple collections`, `mgodatagen` )
  - [x] update documentation  

new syntax possibility: 
```
db = {
    "collection1": [
      {
        "_id": 1,
        "k": 2
      },
      {
        "_id": 2,
        "k": 3
      }
    ],
    "collection2": [
      {
        "_id": 1,
        "k2": 12
      },
      {
        "_id": 2,
        "k2": 2
      }
    ]
  }
```
